# Generated by Django 5.2.5 on 2025-09-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='data_adimissao',
            new_name='data_admissao',
        ),
    ]
