# Generated by Django 5.2.5 on 2025-08-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fornecedore',
            new_name='Fornecedor',
        ),
    ]
